name: blooddonation
description: Blood Donation App from the Hackathon Muenster 2021
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.0-178.0.dev <3.0.0"

dependencies:
  # Infrastructure
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Basic
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.2
  shared_preferences: ^2.0.8
  http: ^0.13.3
  google_fonts: ^2.1.0

  # Visuals
  im_stepper: ^0.1.3
  rive: ^0.7.22
  panorama: ^0.4.1
  table_calendar: ^3.0.2
  introduction_screen: ^2.1.0
  carousel_slider: ^4.0.0
  language_picker: ^0.4.1
  showcaseview: ^1.1.5
  badges: ^2.0.2

  # map
  latlong2: ^0.8.0
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.0

  # Misc
  flutter_local_notifications: ^9.1.5
  crypto: ^3.0.1
  url_launcher: ^6.0.12
  background_fetch: ^1.0.3



dev_dependencies:
  # Dynamic Tests
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

  # Static Tests
  flutter_lints: ^1.0.4

  # Brand Design
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.4
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/localization/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Universit채tsklinikum_M체nster_Logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Universit채tsklinikum_M체nster_Logo.png
