name: blooddonation
description: Blood Donation App from the Hackathon Muenster 2021
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Infrastructure
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Basic
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3
  shared_preferences: ^2.0.8
  http: ^0.13.3
  google_fonts: ^2.1.0

  # Visuals
  im_stepper: ^0.1.3
  flutter_blurhash: ^0.6.0
  empty_widget: ^0.0.5

  # add map
  latlong2: ^0.8.0
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.0
  url_launcher: ^6.0.12

  # Misc
  syncfusion_flutter_calendar: ^19.2.62
  table_calendar: ^3.0.2
  carousel_slider: ^4.0.0
  introduction_screen: ^2.1.0

  # Firebase
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

  # Brand Design
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/Universitätsklinikum_Münster_Logo.png
    - assets/images/image_1.png
    - assets/images/image_2.png
    - assets/images/image_3.png
    - assets/images/image_4.png
    - assets/images/1.png
    - assets/images/daten.json
    - assets/images/UKM_Blutspende_Muenster_Eingang.jpg
    - assets/images/temp_3G_placeholder.jpg
    - assets/images/temp_blooddonation_placeholder.jpg
    - assets/images/temp_blooddonation_placeholder2.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Universitätsklinikum_Münster_Logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Universitätsklinikum_Münster_Logo.png
