name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - ukm

jobs:
  flutter_test:
    name: Run flutter test and analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_android:
    name: Build Android APK and app bundle
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > android/app/google-services.json
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - run: flutter build appbundle

#  build_ios:
#    name: Build iOS
#    needs: [flutter_test]
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "master"
#      - run: flutter pub get
#      - run: flutter clean
#      - run: flutter build ios --release --no-codesign

  build_web:
    name: Build Web
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web